title: Having Fun and Practicing Things
author: ldaro
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog devoted to lucy practicing things. Please don't expect much from this.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
